### PR TITLE
Add announcement list

### PR DESCRIPTION
**Pull request by btcdrak**
Improve communications by providing an opt-in email list for security and release notifications. Requested by many people who don't have time to follow social media or other noisier channels. This list is only for Bitcoin Core security/release announcements.

screenshot-localhost 4000 2016-03-14 10-44-03

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Nice, Concept ACK!

**Comment by laanwj** [comment]
ACK, looks good to me

**Comment by NicolasDorier** [comment]
awesome ACK

**Comment by jonasschnelli** [comment]
utACK

**Pull request merged**
