### PR TITLE
Update EOL dates for 0.16 and 0.17

### PR DESCRIPTION
**Pull request by MarcoFalke**
EOL dates for 0.16 and 0.17 have not been announced, so do that by bumping the date of the previous version by 6 months.

Also, remove historic release dates for software version 0.8 -- 0.14, since we do not list the release dates for versions 0.7 and before.

### CODE REVIEW

**Comment by harding** [comment]
This seems fine to me.  Do these dates need to be discussed somewhere?

**Comment by jnewbery** [comment]
Concept ACK updating the dates.

Do we have a policy for how long the period should be between Maintenance End and EOL?

**Comment by MarcoFalke** [comment]
Not really. And even 0.17. isn't maintained anymore

**Comment by jnewbery** [comment]
Dates seem reasonable to me, but perhaps we should gather ACKs in the next IRC meeting?

**Comment by laanwj** [comment]
ACK, looks good to me

**Comment by MarcoFalke** [comment]
Looks like there haven't been any objections

**Comment by jnewbery** [comment]
ACK cb223fca9f5dd1b69bb14cbaadd983ea12655370

**Pull request merged**
