### PR TITLE
Remove Supporters page

### PR DESCRIPTION
**Pull request by btcdrak**
This seems redundant now and hard to maintain in any case.

### CODE REVIEW

**Comment by jnewbery** [comment]
concept ACK. Will review tomorrow.

**Comment by harding** [comment]
Concept ACK.

Tested LGTM except that there's some leftover CSS specific to the removed page starting at line 997 in `_sass/page.scss`

**Comment by btcdrak** [comment]
@harding removed, can you check it's OK.

**Comment by harding** [comment]
Tested ACK 41a819e6777836de864a91034948517c491a8db3

**Comment by jnewbery** [comment]
Tested ACK 41a819e6777836de864a91034948517c491a8db3 (with thanks to everyone who's shown their support :+1: )

**Comment by btcdrak** [comment]
Needs rebase.

**Comment by btcdrak** [comment]
@harding needs rebase.

**Pull request merged**
