### PR TITLE
Remove bitcoin.pdf

### PR DESCRIPTION
**Pull request by laanwj**
The licensing status of this file is unclear. It can be found in enough places by now, and as this site is about Bitcoin Core (a specific implementation), not about Bitcoin in general, the whitepaper doesn't necessarily need to be hosted here.

Unless anyone can point to an explicit place where Satoshi licensed it under a free license, legally it is safer to remove it from the bitcoin-core.org site.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
ACK c131308cb9cf3538ba9db04a3002a76e6f334f62 checked that this is only removing links, doesn't change content

**Comment by harding** [comment]
About half of the links removed in this PR point to document on the Bitcoin.org server, not the BitcoinCore.org server.  Is that deliberate?  Bitcoin.org has the strongest claim to being able to host the document as that's where Nakamoto first posted it and (AFAIK) he's never asked for it to be removed from there.

If we remove this from the website out of legal concerns, I think that would imply we'd also need to `git filter-branch` rewrite history to remove the document from the git history.  Otherwise, we're still providing the document in some sense.  I don't have an objection to doing this (carefully, with people prepared to verify that's the only change made, and somebody standing by to fix the website hosting verification script if necessary).

I'd personally prefer to continue hosting the document.  Given that Nakamoto shared everything else he did under his psuedonym, I think we can argue that we're acting in good faith by sharing this document also.  That said, I agree it would be legally safer to remove it, hosting it is not a part of Bitcoin Core's mission, and that there are plenty of other copies available elsewhere for those who want to read it.

**Comment by harding** [comment]
Code review ACK c131308cb9cf3538ba9db04a3002a76e6f334f62

**Comment by luke-jr** [comment]
Could have just linked to bitcoin.org? Oh well

(IANAL, but I imagine bitcoin.org at least should have an implicit license to distribute it unmodified since Satoshi himself put it there)

**Comment by Cobra-Bitcoin** [comment]
This was merged really quickly...

**Comment by nopara73** [comment]
It saddens me that fraudsters are bullying open source Bitcoin contribitors. Don't get demotivated though, what you're doing is crucial for the future of humanity. Keep up the hard work guys!

**Comment by cculianu** [comment]
In practice you guys have not followed the original vision proposed by Satoshi in the white paper since about 2015 or so. It's good to know that finally the last nail is in the bitcoin coffin has been hammered-in with this commit. 

You are congratulating yourselves on it --  As if you guys just accomplished a great feat.

Indeed, congratulations are in order.  The mental gymnastics required to participate in BTC these days deserves a congratulatory medal, at the very least.

**Comment by Seccour** [comment]
> The licensing status of this file is unclear. It can be found in enough places by now, and as this site is about Bitcoin Core (a specific implementation), not about Bitcoin in general, the whitepaper doesn't necessarily need to be hosted here.
> 
> Unless anyone can point to an explicit place where Satoshi licensed it under a free license, legally it is safer to remove it from the bitcoin-core.org site.

Here you go: https://web.archive.org/web/20091129231620/https://sourceforge.net/projects/bitcoin/

Feel free to put back the Bitcoin Whitepaper on the site.

Next time instead of complying to threats, you could just make people aware of them and let the community defend you. We shouldn't let bullies like Craig Steven Wright (Who is NOT Satoshi Nakamoto, will never be, and who also never contributed to Bitcoin or wrote any of the content present on the whitepaper) have it their way.

**Comment by pavlenex** [comment]
I understand that contributors want to contribute without spending time on drama. Unfortunately, this will be one of those issues that will cause way more drama and provide material to the "Bitcoin Core Coin" narrative.

Perhaps a link to bitcoin.org would've been better than removal. I don't think we should be bending to these malicious actors. Maybe the [COPA](https://open-patent.org/) alliance can be of help.

**Comment by SamuraiXa** [comment]
> In practice you guys have not followed the original vision proposed by Satoshi in the white paper since about 2015 or so. It's good to know that finally the last nail is in the coffin has been hammered-in with this commit.
> 
> You are congratulating yourselves on it -- As if you guys just accomplished a great feat.
> 
> Indeed, congratulations are in order. The mental gymnastics required to participate in BTC these days deserves a congratulatory medal, at the very least.

Your opinion is irrelevant. 
Bcash is centralized.

**Comment by karozagorus** [comment]
You guys are fucking idiots for removing it.

**Comment by karozagorus** [comment]
Seriously @laanwj, you are giving more power to the fraud called Craig Steven Wright, you immediately caved like a coward. He been attacking my friend, Hodlonaut, in UK court for over 2 years now, and you guys just keep credence to him. Thanks, seriously. I'm starting to seriously believe you guys seriously don't consider the bigger picture ever.

**Comment by aviv57** [comment]
This is ridiculous, 
The bitcoin white paper is public, we want it to be in bitcoincore.org.

**Comment by SamuraiXa** [comment]
Without the whitepaper on bitcoincore.org, how would I know I'm running the right Bitcoin ?!

**Comment by sosojni** [comment]
Is this for real? Are you for real?

**Comment by Iamtutut** [comment]
I didn't think there would be such cowardice by @laanwj
The copyright office doesn't very the merits of a claim, it just registers it. Period. They stated on their website (may 22 2019):
https://www.copyright.gov/press-media-info/press-updates.html?loclr=twcop

See also for reference: https://thebitcoinnews.com/us-copyright-office-responds-to-craig-wrights-bitcoin-registrations/
- Arthur VAN PELT in Holland is also registred as the owner of the Whitepaper: TX0008745988 / 2019-05-21
- Jurgen Etienne Guido DEBO is also registred as the owner of the Whitepaper: TXu002162384 / 2019-05-22 
- "Satoshi Nakamoto" per se is also registred as the owner of the Whitepaper: TX0008749890 / 2019-05-30
- Satoshi Nakamoto, pseud. of WEI LIU is also registred as the owner of the Whitepaper: TX0008726120 / 2019-05-24
- ....

The licensing is CRISTAL CLEAR: The WP was released in the cypherpunk mailing list that has an anti copyright policy to any content distributed there, plus the code is under MIT license.
Nobody can enforce any other kind of licensing. You can ask Stephan Kinsella (patent attorney) hos opinion on the subject: https://twitter.com/NSKinsella

The WP ought to be on the bitcoin core site and repo.

**Comment by midnightmagic** [comment]
Based on the timing, and the lack of knowledge about the fact that the jerkwad also sent demand letters to a half dozen other places, wumpus et al did a reasonable thing. It's not like there's not plenty of options now. Get off their back, fools, unless you have the hundreds of thousands it takes to mount a vigourous legal defence and want to put it in a defence trust.

All y'all's perspective right now is retrospectively knowing that the demand letters were sent, and were sent to multiple other victims. This was not knowledge almost anyone had even just a few hours ago.

**Comment by godSaysHODL** [comment]
anyone who ACK'd this, should be removed from the ability to merge

**Comment by karozagorus** [comment]
@harding and @MarcoFalke are both complicit.

**Comment by chovy** [comment]
maybe you guys can fix the $14 fee problem rather than this horseshit.

**Comment by Sjors** [comment]
There's not much we can do in the short run about bullying lawyers, but there is something we can do about unhinged commenters. I suggest locking this thread :-)

**Comment by beeforbacon** [comment]
Can someone put up a pull request to reinstate the white paper? Thanks.

**Comment by karozagorus** [comment]
@Sjors we have the right to debate this, Bitcoin is everyone's.

**Comment by godSaysHODL** [comment]
> maybe you guys can fix the $14 fee problem rather than this horseshit.

The mempool has not gone above a 10 dollar need to get into the next block since 2017, so maybe learn how to set your own fee or use lightning  before you hop on board with scams.

**Pull request merged**
