### PR TITLE
Releases: 0.20.0

### PR DESCRIPTION
**Pull request by harding**
This PR adds the standard release notes, short release blog post (listed on the homepage), and HTML-ized RPC documentation (generated using the script in `contrib/doc-gen`).  Todos:

* [x]  Update dates (rename the `_posts` file and edit the YAML `date` field in the `_releases` file)
* [x]  Optional: add magnet link to the `_releases` file
 
Note: tests expect to fail until the binaries have been uploaded to `/bin/`. After that's done, restart Travis and it should pass.

CC: Sjors to whitelist the magnet hash on his torrent tracker (e.g. https://github.com/bitcoin-core/bitcoincore.org/pull/698#issuecomment-596678739 )

### CODE REVIEW

**Comment by laanwj** [comment]
Thanks! Binaries have been uploaded so will fill in the missing parts.

**Comment by laanwj** [comment]
ACK cbe1ca9d1b6aac6854880f09cd76f0d19b297267

**Comment by laanwj** [comment]
@Sjors please whitelist the torrent hash 1845a0c66b6a728e183b9bd8c5d8c1611dddaaa3 on your tracker

**Comment by Sjors** [comment]
@laanwj done

**Pull request merged**
