### PR TITLE
Add search bar for rpc docs

### PR DESCRIPTION
**Pull request by n1rna**
This PR is addressing the problem of finding docs for one specific rpc command by its name. In the website one can not simply find his/her desired command in the menu. One should open all the parent categories (`Blockchain`, `Control`, etc) and then use Ctrl+F to find the command.

I have added a little javascript code to handle the string search between all commands and make this process much easier.

### CODE REVIEW

**Comment by harding** [comment]
Concept ACK.  This is very nice and a much smaller amount of code than I would've expected.  Thanks!  Two comments:

1. Can you use `<noscript>` (or whatever) to hide the search box if JS is disabled?

2. I think it's a little hard to see the search box.  Do you or anyone else have any suggestions for making it more visible?  Maybe just give it a grey background instead of white?

**Comment by n1rna** [comment]
Your comments are addressed in https://github.com/bitcoin-core/bitcoincore.org/pull/722/commits/caee34dbf4c452c334a364f873fb447c4f24783b @harding

**Comment by harding** [comment]
Tested ACK caee34dbf4c452c334a364f873fb447c4f24783b Reviewed code, tested with Chromium, Firefox with NoJS, and Firefox with JS enabled.  Made several searches and didn't see anything odd.  Ran all repository tests.

I'll leave this open for the rest of the weekend in case anyone else wants to review; if there are no problems, I hope to merge Monday.  Thanks @n1rna!

**Comment by n1rna** [comment]
> Thanks @n1rna!

Thanks @harding ! Hope it helps other developers find what they're looking for faster xD

**Comment by harding** [comment]
Note.  I don't have the ability to merge this because the Travis check hasn't passed (it's stuck on "Expected---waiting for status to be reported"; the tests pass for me locally).  I don't have access to kick Travis or push a merge anyway.  I asked for help on #bitcoin-core-dev but nobody responded, so this PR is stuck.  :-(

**Comment by MarcoFalke** [comment]
I'll let you know when I hear back from travis. It is their faulty abuse detection: https://travis-ci.org/github/bitcoin-core/bitcoincore.org/requests

**Comment by harding** [comment]
@MarcoFalke thank you!

**Comment by MarcoFalke** [comment]
I think the best would be to disable the ci requirement long term.

Not sure if close-open does help now, but you could try.

> Our system automatically flagged your account for possible abuse, but after further review, we were able to clear that up. You should be all set to build as normal, though please feel free to contact us should you have any questions or concerns arise.

**Comment by n1rna** [comment]
Thanks @MarcoFalke

**Pull request merged**
