### PR TITLE
contrib: Trusted keys cleanup phase 1

### PR DESCRIPTION
**Pull request by laanwj**
Trusted keys cleanup phase 1: Update the trusted git root.

This is done in two parts to prevent the automatic update on the site from being broken.

This is step one in removing the following inactive keys:
```
32EE5C4C3FA15CCADB46ABE529D4BCB6416F53EC  jonasschnelli (last use: f324ce32f53e7b0b149f9e7e83874ac4ff5fb92f in 2018)
1E7DD3547F244C757223FAC8FC6434FC3A31E956  btcdrak (never used?)
912FD3228387123DC97E0E57D5566241A0295FA9  btcdrak (last use: 32b7869956e3a70025e32b69bab11fc262ef84d8 in 2017)
```

The most recent of these commits is f324ce32f53e7b0b149f9e7e83874ac4ff5fb92f, so update the merge base to that.

In the next phase I will actually remove these keys, leaving the following keys (I have tested this trusted root by replacing the contents of `contrib/verify-commits/trusted-keys` and running the verify-commits script):
```
831524AA4329D0B9E85E30ABD9DB41A96C2269D3  harding
71A3B16735405025D447E8F274810B012346C9A6  laanwj
E777299FC265DD04793070EB944D35F9AC3DB76A  fanquake
```

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Concept ACK

**Comment by MarcoFalke** [comment]
phase 2 can also revert https://github.com/bitcoin-core/bitcoincore.org/pull/599

**Review by fanquake — APPROVED** [review]
utACK c6642424a7fdd67fc7abb692a578532a8732fe6f

**Comment by fanquake** [comment]
@laanwj did you want to follow up with a second phase here?

**Comment by laanwj** [comment]
Yes, it should be ok to do so now.

**Pull request merged**
