### PR TITLE
Revert "Remove bitcoin.pdf"

### PR DESCRIPTION
**Pull request by Legogris**
This reverts commit c131308cb9cf3538ba9db04a3002a76e6f334f62 in PR #740.

### CODE REVIEW

**Comment by i-rme** [comment]
**Some proof that Bitcoin.pdf is MIT licensed**

In March 2009, nakamoto2 added the bitcoin.pdf file with License: MIT License to Sourceforge.

image
https://web.archive.org/web/20090106201347/https://sourceforge.net/projects/bitcoin/

**Comment by Cobra-Bitcoin** [comment]
ACK.

**Comment by kFTY** [comment]
> **Some proof that Bitcoin.pdf is MIT licensed**
> 
> In March 2009, nakamoto2 added the bitcoin.pdf file with License: MIT License to Sourceforge.
> 
> image
> https://web.archive.org/web/20090106201347/https://sourceforge.net/projects/bitcoin/

MIT license is only valid for software

> including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the **Software**

**Comment by Cobra-Bitcoin** [comment]
> Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and **associated documentation files** (the "Software")

@kFTY

**Comment by i-rme** [comment]
> MIT license is only valid for software
> 
> > including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the **Software**

No, it's on the first line of the license text:

```Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software")```

The software and associated documentation files is called the Software.

Also we could argue that a PDF file is software as a set of instructions.

**Comment by zangornjak** [comment]
The pussy in some of the commenters is immense.

**Comment by randomhouse** [comment]
Wait a while before merging so as not to repeat the procedural mistake of https://github.com/bitcoin-core/bitcoincore.org/pull/740 . Allow time for this PR to win all challenges. No rush ;)

**Comment by Legogris** [comment]
> @harding didn't provide enough time for the MIT license to be shared or for any comment to support the claim that a license was not known.

Assigning blame is not relevant to this PR.

**Comment by randomhouse** [comment]
I don't like pointing out an individual either, so I've deleted my comment. But, this PR exists because merging procedure was broken. That needs to be reviewed.

**Pull request closed without merging**
