### PR TITLE
RPC Docs: add 22.0.0

### PR DESCRIPTION
**Pull request by andrewtoth**
Generated using this repo's `contrib/doc-gen/generate.go`. The first commit is updating that script to use the new version scheme introduced in 22.0.0.

Should be fully deterministic, so anyone wanting to review can install 22.0.0 and run the following:
```
bitcoind --daemon --regtest
cd contrib/doc-gen
go run generate.go
```

I lightly tested a local preview and didn't see anything broken this release.

Closes https://github.com/bitcoin-core/bitcoincore.org/issues/820.

### CODE REVIEW

**Comment by Sjors** [comment]
utACK ee81ea6

I was able to reproduce the same docs, but haven't tested locally yet.

**Comment by harding** [comment]
Tested ACK ee81ea6b250ddcbd36f0d1dc31e572382c00bfc3 Thanks!

**Comment by katesalazar** [comment]
> Dropping the trailing `0` would be good:
> Schermafbeelding 2021-12-17 om 09 50 29

I saw this too, but checked places on bitcoin where 22.0.0 is presented, the very bump rev IIRC.
This is acceptable as it is.

**Comment by katesalazar** [comment]
v23 is tagged now :))

**Pull request merged**
