### PR TITLE
 Change all local links to be relative (rebased)

### PR DESCRIPTION
**Pull request by carnhofdaki**
This is a rebased https://github.com/bitcoin-core/bitcoincore.org/pull/741, nothing added and did not even check if new absolute links need `{{ ROOT_PATH }}`.

### CODE REVIEW

**Comment by laanwj** [comment]
Looks like there's a lot of HTMLproofer errors in finding the release binaries. I don't know if this is a problem with the generated HTML or the tool.

**Comment by katesalazar** [comment]
no longer your can of worms 😂

**Comment by MarcoFalke** [comment]
Can this be closed?

**Comment by carnhofdaki** [comment]
Sure. Closing.

**Pull request closed without merging**
