### PR TITLE
Meetings: add 2018-05-17

### PR DESCRIPTION
**Pull request by harding**
Preview: http://dg1.dtrt.org/en/meetings/2018/05/17/

### CODE REVIEW

**Comment by MarcoFalke** [comment]
ACK 2cdce9c5af12403f13ac623639859c65161e531f

**Comment by jnewbery** [comment]
ACK 2cdce9c5af12403f13ac623639859c65161e531f

Thanks as always @harding - these are a really great resource.

**Comment by MarcoFalke** [comment]
Can someone please merge this? It seems ready for merge

**Comment by harding** [comment]
@MarcoFalke the GitHub settings for this repository require an Approving Review (through the GitHub UI) from someone with commit access who is not the person who opened the PR, so I can't merge this myself even though I do think it has a sufficient number of acks.  Something to discuss (maybe on IRC) is giving commit access on this repository to additional people, such as yourself, who frequently review PRs here so that they can give approving reviews.

Alternatives would be (1) moving weekly meeting posts and possibly blog posts in general to a separate repository and subdomain that doesn't require the same GitHub-enforced threshold for merging, or (2) changing the repository settings so that people with commit access can merge their own PRs without an approving review from someone with commit access, enforcing the needs-appropriate-number-of-ACKs policy the old fashioned way by yelling at people who merge too soon (or, ultimately, by taking away their commit access).

**Comment by MarcoFalke** [comment]
@btcdrak @jonasschnelli @laanwj  Mind to unblock the merge?

**Comment by jnewbery** [comment]
approved! :+1:

**Comment by harding** [comment]
Thanks whoever(s) made this possible!

**Pull request merged**
