### PR TITLE
 Remove more unused (sample) images 

### PR DESCRIPTION
**Pull request by MarcoFalke**

### CODE REVIEW

**Comment by Sjors** [comment]
Concept ACK, but I didn't check if the assets are actually unused.

**Review by fanquake — APPROVED** [review]
ACK 0b32e162a1b2aa0f3f57fde1ef9ce62ca55506e6

**Comment by katesalazar** [comment]
> didn't check if the assets are actually unused.

    $ grep -r asset.yml . && grep -r bitcoin-310 . && grep -r sample-image .
    $ 

ACK 0b32e162a1b2aa0f3f57fde1ef9ce62ca55506e6

**Comment by katesalazar** [comment]
https://github.com/bitcoin-core/bitcoincore.org/blob/fabd138905877a23d582444e0487b187b2cb2f07/_config.yml#L65

**Comment by MarcoFalke** [comment]
Thx, fixed.

**Comment by katesalazar** [comment]
ACK ba906b8a88a7c3ece9aacffa5a96b8cd0e816a4a

**Review by Zero-1729 — COMMENTED** [review]
ACK ba906b8a88a7c3ece9aacffa5a96b8cd0e816a4a

LGTM

**Pull request merged**
