### PR TITLE
lifecycle: drop now past-EOL 22.x

### PR DESCRIPTION
**Pull request by fanquake**
Remove 22.x from the liftcycle table.

### CODE REVIEW

**Comment by katesalazar** [comment]
ACK 25125af7227b9f121ceacefedb6e1e5fb231c853

**Review by Zero-1729 — COMMENTED** [review]
LGTM

crACK 25125af7227b9f121ceacefedb6e1e5fb231c853

**Comment by katesalazar** [comment]
trivial to rewind

**Comment by fanquake** [comment]
cc @glozow @achow101

**Review by glozow — COMMENTED** [review]
utACK 25125af7227b9f121ceacefedb6e1e5fb231c853

**Pull request merged**
