### PR TITLE
2016-01-01-meetings.md: Switch to #bitcoin-core-dev?

### PR DESCRIPTION
**Pull request by MarcoFalke**
Did we switch officially?

### CODE REVIEW

**Comment by jonasschnelli** [comment]
No. There was no meetingbot in #bitcoin-dev anymore. Somebody should announce or ask for a "official" switch to #bitcoin-core-dev.

**Comment by MarcoFalke** [comment]
https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2016-March/012484.html

**Comment by MarcoFalke** [comment]
@btcdrak looks like you already fixed it on the website. I think you still need to bump the version to get the fresh translations on transifex?

**Comment by btcdrak** [comment]
Woops. I forgot about this PR

Updated in https://github.com/bitcoin-core/bitcoincore.org/commit/16ece3641f40add8bddd356493b6e42b7ec86e2f and https://github.com/bitcoin-core/bitcoincore.org/commit/f3780b65537ea44aee16dbcb49a08bf85436137a and

**Pull request closed without merging**
