### PR TITLE
Colourise segwit adoption table

### PR DESCRIPTION
**Pull request by ajtowns**
Here's a patch to add background colours to the segwit adoption table -- makes it a bit easier to spot which ones aren't done yet. Not sure if there's a meaningful difference between "wip" and "no"; I left "wip" as normal background but maybe it should be coloured "bad" too.

I couldn't get kramdown markup to add an attribute to cells, so switched to using liquid to generate HTML directly based on a CSV file, which seems fine. I chose yellow and blue because it seems to work for colour blind (unlike green and red), doesn't suffer from red is bad in the West and good in the East confusion, and because "golden" sounds positive and "blue" is sad, but whatever.

Also added a URL for NBitcoin since it was the only one missing a URL and it saved special casing it.

### CODE REVIEW

**Comment by ajtowns** [comment]
Here's what it looks like for me fwiw:

image

**Comment by btcdrak** [comment]
In most cases "wip" means it's been done, but is in a development branch or hasn't been merged.

**Comment by btcdrak** [comment]
Maybe yes should be green.

**Comment by ajtowns** [comment]
> Maybe yes should be green.

Green/blue is confusing to some people I think, http://www.color-blindness.com/2007/05/18/mixing-up-blue-and-green/ and at least 0x9fd (green) vs 0x9df (blue) performs pretty poorly on http://www.color-blindness.com/coblis-color-blindness-simulator/

Green/yellow (cfe/ffb) seems okay though: 
segwit-gy

**Comment by btcdrak** [comment]
Yeah, that works too.

**Pull request merged**
