### PR TITLE
Remove "Share On" links

### PR DESCRIPTION
**Pull request by MarcoFalke**
Google Plus has long been dead and removed from the internet and the Bitcoin Core project website is the wrong place to advertise or promote (not yet dead) social networks anyway.

### CODE REVIEW

**Comment by jnewbery** [comment]
tACK fa1301aec2bb548170d3f5d0ee268defca621db3

**Comment by MarcoFalke** [comment]
Anything left to do here?

**Comment by harding** [comment]
@MarcoFalke needs rebase, sorry.

**Comment by MarcoFalke** [comment]
Rebased

**Comment by harding** [comment]
Tested ACK fa021b7bd7500acef31ea1aa94b59bc256f68d21

**Pull request merged**
