### PR TITLE
Add post correcting some misunderstandings around btc1/segwit2x

### PR DESCRIPTION
**Pull request by TheBlueMatt**
This post was written collaboratively after the IRC meeting yesterday and has been reviewed by ~all relevant parties.

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
Tweaked to refer to BCH as "the creation of the BCH currency". Sadly I dont think there's any consensus to make explicit reference to the NYA. While its true that no one who regularly contributes to Core went, that was a series of individual decisions to decline to participate, not a joint Bitcoin-Core-did-X thing.

**Comment by achow101** [comment]
ACK

**Comment by jonasschnelli** [comment]
ACK

**Comment by luke-jr** [comment]
@TheBlueMatt Regardless of how the decisions not to participate were made, it is a fact that Core as a whole didn't participate.

**Comment by morcos** [comment]
It's hard to get a post out that is perfect, but this one is pretty good.
For the record though, I agree with @luke-jr that it could have been nice to add that no one representing Core and in fact no one who even contributes to Core was party to the agreement.

**Pull request merged**
