### PR TITLE
Add spanish translation of 0.21.2

### PR DESCRIPTION
**Pull request by katesalazar**
Attempts to exactly mimic #810 for spanish language,
meaning format issues in #810 directly apply here as well.

Untested at the time of submitting.

### CODE REVIEW

**Comment by katesalazar** [comment]
Last Ruby site I contributed a translation to,
had been a less bumpy contribution. 🤷‍♀️

**Comment by katesalazar** [comment]
I force pushed, no content changes since 872544edfcc7,
I only reorganized the changes in 4 commits. 🤔

**Comment by katesalazar** [comment]
I forced push again, only to apply 451ad1a58893c43b4351152d1ed449ddeeabebf9 here.

**Comment by harding** [comment]
Tested ACK 9b2ced7257d8dff08a57cce364606de819037a1a using Google Translate to verify text.  Thanks!

I did find the following reverse translation amusing (the actual translation looks good to me):

latest

**Comment by katesalazar** [comment]
shoulda used "colaborador" :/

**Pull request merged**
