### PR TITLE
update trusted-keys: remove harding, add achow101 and glozow keys

### PR DESCRIPTION
**Pull request by glozow**

### CODE REVIEW

**Comment by glozow** [comment]
Already pinged offline but cc @harding @achow101

**Comment by achow101** [comment]
ACK e71e72c816ad92622d691435887e690d7f55e4df

The keys added match the fingerprints I have for my own key and glozow. The key removed says it belongs to harding, although I did not have it locally before.

As harding does not have the necessary permissions to merge anything, it makes sense to remove his key.

I had asked glozow to add my key when she mentioned she would open a PR to add herself.

**Comment by pinheadmz** [comment]
concept ACK

The key list matches bitcoin core with the exception of hebasto (`D1DBF2C4B96F2DEBF4C16654410108112E7EA81F`) is there a reason for that?

**Comment by glozow** [comment]
> is there a reason for that?

hebasto didn't ask me to add his key in this PR, that's all

**Review by pinheadmz — APPROVED** [review]
ACK e71e72c816ad92622d691435887e690d7f55e4df
<details><summary>Show Signature</summary>

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

ACK e71e72c816ad92622d691435887e690d7f55e4df
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEE5hdzzW4BBA4vG9eM5+KYS2KJyToFAmQi9IEACgkQ5+KYS2KJ
yTqycA//W/QQuyEpduvB+n/jOwW009GnQRyuDTDXHrs1lcLsFGJIu+niMfY91zGq
TimWT7laH4FUBoO8fzh7l5wBu8E9y1PeoaoL73GgfPZu6Z6WYCKhlwW4sBL6od6k
4HpKMIXCh/JnQTuvv8htZ37Fm61W3f5THoQBEXfcvB81l23s8z8dca9/xwPcC5Dh
UhhjKzOyx+ygstpCl6X9OoEp31MwFIqSFbup8JLEiUmqIA4UqlOwL6t/sAXHYyNj
yAAaZQlIj4VumGeyXNVOC/ueYY6Ywba3g0r8iPSg8nzyRhtBlTAL8rp7rW+AgCUq
O9TgmyW3LAJHNEkHgAdU0kJRl+X4u4kfNk1nhadcaERHx1vN3kiLtpm2/+gvY0u4
UGrEF/2dC2HTT6B1BhG8VS7O95VkCM7vpcAxWmlLyREN6P4gbOaseDiEUibNyn2S
zHGkAAReqdtLSQzkDqWmhvgX4Six4jL7sRF146Wxkb6XOlTY7u2zBqvbFdrSBfnj
pwiExr5g/NnZ56iPe3x0i0CN/7wodAhmnIuAWzpY4SAdC5sx1/PjMu893rwKKvVb
1SeTpYW5klqXIiNWf799ZWAWLoQeHaGbhxi8DNnLwyz2tSx2YXFUNxMj+rTdKLuC
8SfI2Y0kOJxLpFkqkNMhKyqG87jvI3VHKE6cUuieJWryvjBeD1E=
=eHXO
-----END PGP SIGNATURE-----
```

pinheadmz's public key is [on keybase](https://keybase.io/pinheadmz/pgp_keys.asc?fingerprint=e61773cd6e01040e2f1bd78ce7e2984b6289c93a)
</details>

**Comment by hebasto** [comment]
> > is there a reason for that?
> 
> hebasto didn't ask me to add his key in this PR, that's all

Confirming :)

**Comment by RandyMcMillan** [comment]
https://raw.githubusercontent.com/bitcoin/bitcoin/master/contrib/verify-commits/trusted-keys

patch:

```
diff --git a/contrib/verify-commits/trusted-keys b/contrib/verify-commits/trusted-keys
index c919d84..94daf28 100644
--- a/contrib/verify-commits/trusted-keys
+++ b/contrib/verify-commits/trusted-keys
@@ -1,3 +1,4 @@
 E777299FC265DD04793070EB944D35F9AC3DB76A
+D1DBF2C4B96F2DEBF4C16654410108112E7EA81F
 152812300785C96444D3334D17565732E08E5E41
 6B002C6EA3F91B1B0DF0C9BC8F617F1200A6D25C

```

**Pull request merged**
