### PR TITLE
Update lifecycle schedule

### PR DESCRIPTION
**Pull request by MeshCollider**
Now 0.17 has been released, update the schedule to include 0.15 Maintenance End and EOL. Will discuss the date in this weeks meeting.

### CODE REVIEW

**Comment by harding** [comment]
@MeshCollider I'm confused by "will discuss the date in this week's meeting".  Does that mean the date in this PR is tentative?

**Comment by MeshCollider** [comment]
@harding the EOL date for 0.15 should be fine, but it pays to check with the others just to make sure.

**Comment by harding** [comment]
@MeshCollider ok.  I'll wait to check the meeting log to see how the discussion went before I consider merging (I did preview, and it LGTM).  Thanks!

**Comment by laanwj** [comment]
ACK

**Comment by MeshCollider** [comment]
Alright, consensus from meeting is that this date is fine @harding
Feel free to merge :)

**Comment by jnewbery** [comment]
ACK the dates. Minor nit: I wouldn't add the row for 0.19 yet, but I'm not going to bikeshed this.

IRC log: http://www.erisian.com.au/bitcoin-core-dev/log-2018-11-08.html#l-619

**Pull request merged**
