### PR TITLE
trivial: Fixed typo 

### PR DESCRIPTION
**Pull request by merland**

### CODE REVIEW

**Comment by karel-3d** [comment]
ACK

**Comment by jnewbery** [comment]
I *think* the text is ok as is, since it's referring to multiple versioning systems, but I'll defer to the @harding stylebook on this one.

**Comment by merland** [comment]
@jnewbery Thanks for weighing in. 
This clearly is an honest typing mistake. Nobody says "versions numbers", right?

**Comment by harding** [comment]
It's wrong, probably an editing mistake on my part where I rearranged the sentence.  ACK.

**Pull request merged**
