### PR TITLE
maintenance: correct `v22.1` release date

### PR DESCRIPTION
**Pull request by fanquake**
`v22.1` became available on 14th December 2022, see: https://bitcoincore.org/bin/bitcoin-core-22.1/.

### CODE REVIEW

**Review by dergoegge — APPROVED** [review]
ACK 472bcdcbfe1e4579f571c39a5d533f07b37c67ae

**Comment by fanquake** [comment]
Fixed another date.

**Review by glozow — COMMENTED** [review]
ACK cfeeadb4a87fa81959f16571c09906b45cfbfaaf

**Review by stickies-v — APPROVED** [review]
ACK cfeeadb4a87fa81959f16571c09906b45cfbfaaf

**Pull request merged**
