### PR TITLE
Add ShapeShift.io

### PR DESCRIPTION
**Pull request by shapeshiftMatt**
ShapeShift.io recently added segwit support.

### CODE REVIEW

**Comment by Showerhaed** [comment]
Nah.

**Comment by luke-jr** [comment]
Using Bitcoin Core's wallet? (indicated by the last column)

Also, you have an extra comma.

Finally, isn't ShapeShift.io planning to defect to 2X in a month?

**Comment by shapeshiftMatt** [comment]
Hey Luke-jr,

Yes, I can confirm we are running bitcoin 15.0.1 core in production so that is accurate.

And I removed the trailing comma,

Thanks.

**Comment by jonasschnelli** [comment]
ACK after squash.

**Comment by shapeshiftMatt** [comment]
Mixed up accounts in my haste, see https://github.com/bitcoin-core/bitcoincore.org/pull/451

**Pull request closed without merging**
