### PR TITLE
Bump Approx disk size to 400 Gb

### PR DESCRIPTION
**Pull request by RandyMcMillan**

### CODE REVIEW

**Comment by Sjors** [comment]
400 should be enough for now: https://github.com/bitcoin/bitcoin/blame/v0.21.0rc2/src/chainparams.cpp#L108

**Comment by RandyMcMillan** [comment]
@Sjors done

**Comment by Sjors** [comment]
ACK 2868084

**Comment by jonasschnelli** [comment]
My current blocks dir is 332GB. I think 400gb is enough for now but that number should bump soon again.
It's a bad experience if people buy disk space according to this number then figure "weeks" later out that its not enough to sync further (without prune).

**Comment by harding** [comment]
@jonasschnelli I think it's fine.  The variable is used with this text on the [Download page](https://bitcoincore.org/en/download/):

> Bitcoin Core requires a one-time download of about 300GB of data plus a further 5-10GB per month. By default, you will need to store all of that data, but if you enable pruning, you can store as little as 6GB total without sacrificing any security. For more information about setting up Bitcoin Core, please read the full node guide.

**Comment by harding** [comment]
ACK 2868084e467bb08fd644dd43586ebb5485516f41

**Pull request merged**
