### PR TITLE
Add portugues transalation to ABOUT page

### PR DESCRIPTION
**Pull request by mateusnds**
I'm starting to translate the site into Portuguese, this is the first page I'm doing and I hope everything goes well-. If I'm doing something wrong, please let me know.

Use this page to open Pull requests for changes to the Bitcoin Core project
website at [bitcoincore.org](https://bitcoincore.org).

### CODE REVIEW

**Comment by mateusnds** [comment]
Hello, Whats is this RSS failed?

**Comment by katesalazar** [comment]
> Hello, Whats is this RSS failed?

This "RSS failed" is an alert telling everybody
that your proposed changes would break the site
in a predictable way.

To break the site, you have to do so
in a non predictable way.

**Comment by mateusnds** [comment]
> > Olá, O que é este atrasou RSS?
> 
> Este "RSS a esperada" é um alertando todas as suas alterações que cumpririam o site de uma esperança esperada.
> 
> Para quebrar o site, você deve fazê-lo de forma não previsível.

Thanks for the answer.

Do you know how I can translate without "breaking the site"?

I followed the readme documentation and just translated the strings from the file, so I still can't understand what's wrong.

**Comment by katesalazar** [comment]
> Do you know how I can translate without "breaking the site"?
> 
> I followed the readme documentation and just translated the strings from the file, so I still can't understand what's wrong.

What's wrong is that existing links break or new links are created pointing to nowhere.
Whatever it is failing in each of your PRs,
it's explained in each failure "details".

You can use a top-down approach by taking another language translation PR
and replacing the locale language translation for portuguese.

You can use a bottom-up approach by cycling rounds of hunting down CI failures and reviewer comments.

**Comment by mateusnds** [comment]
> > Do you know how I can translate without "breaking the site"?
> > I followed the readme documentation and just translated the strings from the file, so I still can't understand what's wrong.
> 
> What's wrong is that existing links break or new links are created pointing to nowhere. Whatever it is failing in each of your PRs, it's explained in each failure "details".
> 
> You can use a top-down approach by taking another language translation PR and replacing the locale language translation for portuguese.
> 
> You can use a bottom-up approach by cycling rounds of hunting down CI failures and reviewer comments.

Thank you Kate.

I will try to add pt-br/rss page

Regards

**Review by katesalazar — CHANGES_REQUESTED** [review]
> - ./_site/pt-BR/index.html
>  *  internally linking to /pt-BR/rss/, which does not exist (line 243)
>     <a href="/pt-BR/rss/">RSS rss feeds width="14" height="14"></a>
> htmlproofer 3.14.1 | Error:  HTML-Proofer found 1 failure!
> make: *** [Makefile:15: test-slow] Error 1

It seems that the RSS page has to be added with or before this page,
not after.

**Pull request closed without merging**
