### PR TITLE
Meeting summaries for 2016-08-18

### PR DESCRIPTION
**Pull request by G1lius**

### CODE REVIEW

**Comment by btcdrak** [comment]
@harding do you know what happened with Travis here? it's not being triggered.

**Comment by harding** [comment]
@G1lius Hey, I'm investigating the Travis issue and it seems like a number of your recent PRs haven't been tested:



Looking at several of those old PRs, I notice that they say they came from an "unknown repository":



And looking at your repository, I notice that it looks like a near copy of the main repository (including branches).  All this together makes me suspect that after each PR you make, you're deleting and then re-forking your repository?  Is that correct?  (There's nothing wrong with that; I can see how it makes sense if you're always editing through the GitHub web editor.)

I'm wondering if this is the source of the problem, although I can't think of a good reason Travis wouldn't test PRs from a freshly-initialized repository.  @G1lius did you make any changes to your workflow between the 21 July and 28 July meeting summaries that could help us figure this out?

After we publish the blog post for 0.13.0, I can try deleting my repository and opening a test PR through the GitHub web editor to see if I can reproduce the problem.

**Comment by btcdrak** [comment]
Just for background I am going to activate a repository feature right after I post which prohibits any PR to be merged if CI does not pass. Also I am working on adding the merge and verify toolset from

**Comment by btcdrak** [comment]
Just for background I am going to activate a repository feature right after I post which prohibits any PR to be merged if CI does not pass. Also I am working on adding the merge and verify toolset from the bitcoin source repository and no longer use the UI for merging. All merges must be signed. I'll introduce a PR later.

**Comment by harding** [comment]
@btcdrak isn't that GitHub feature that doesn't let you push to a branch unless it passed all status checks incompatible with signed merges (which are usually direct pushed from the merger's computer to the master branch and so not checked by CI)?

**Comment by G1lius** [comment]
@harding I indeed re-fork every time, I've been doing that since the beginning. I haven't changed my workflow, but I did make an extra commit to fix links so it probably triggered when I did that.

**Comment by btcdrak** [comment]
@harding Cant check until travis is working again. Maybe we need a master branch for travis to work properly?

**Pull request merged**
