### PR TITLE
Bitcoin Core 0.16.2

### PR DESCRIPTION
**Pull request by laanwj**
can be merged if it passes travis

### CODE REVIEW

**Comment by harding** [comment]
Oh, we already had #582 open.

**Comment by harding** [comment]
Weird.  This fails because it says the torrent file is missing, but I see it listed in https://bitcoincore.org/bin/bitcoin-core-0.16.2/ .  But but, if I click on it, it 404s.

**Comment by ken2812221** [comment]
Got 403 here
image

**Comment by laanwj** [comment]
oh, sorry, will close and check the file
might be a permissions issue though my upload script is supposed to normalize those

**Pull request closed without merging**
