### PR TITLE
Remove roadmap from 2015

### PR DESCRIPTION
**Pull request by MarcoFalke**
The roadmap has many issues:

* It is outdated and (obviously) does not reflect the current state.
* It implies that there is a unique roadmap for the whole project. However, practically each contributor has their own roadmap.
* The embedded video is likely a GDPR cookie violation.

Fix all issues by removing it.

I think in the future it might be better for contributor(s) to share roadmaps not on this project's website, but on the appropriate mailing list, a blog, or a GitHub gist, or somewhere else.
Also, general bitcoin education content is better hosted on websites dedicated to hosting educational content.

### CODE REVIEW

**Comment by katesalazar** [comment]
Hi, please forgive me for stacking
just a couple of small immediate thoughts

On Mon, Jan 17, 2022 at 12:32 PM MarcoFalke ***@***.***>
wrote:

> The roadmap has many issues:
>
>    - It is outdated and (obviously) does not reflect the current state.
>
> Why not just append a text telling this?

>
>    - It implies that there is a unique roadmap for the whole project.
>    However, practically each contributor has their own roadmap.
>
> Present this as a feature. Again,
why not just append a text telling this?

**Comment by katesalazar** [comment]
Hi, please forgive me for stacking
just a couple of small immediate thoughts

> The roadmap has many issues:
>
>    - It is outdated and (obviously) does not reflect the current state.

Why not just append a text telling this?

>    - It implies that there is a unique roadmap for the whole project.
>    However, practically each contributor has their own roadmap.

Present this as a feature. Again,
why not just append a text telling this?

>
>    - The embedded video is likely a GDPR cookie violation.
>
> Fix all issues by removing it.
>
> I think in the future it might be better for contributor(s) to share
> roadmaps not on this project's website, but on the appropriate mailing
> list, a blog, or a GitHub gist, or somewhere else.
> Also, general bitcoin education content is better hosted on websites
> dedicated to hosting educational content.

**Comment by michaelfolkson** [comment]
ACK

It seems reasonable not to have historical bitcoin-dev mailing list posts also stored on the bitcoincore.org site.

> The embedded video is likely a GDPR cookie violation.

Can you explain why embedded video links are likely a GDPR cookie violation? Do you have any further details on this?

**Comment by MarcoFalke** [comment]
> Can you explain why embedded video links are likely a GDPR cookie violation? Do you have any further details on this?

Links aren't an issue, but iframes might be.

**Comment by TheBlueMatt** [comment]
The website is not hosted in the EU, GDPR does not apply. It seems wasteful to break the many links to this post.

**Comment by MarcoFalke** [comment]
Not a lawyer, but I am pretty sure that GDPR applies based on the location of the individual that the data is collected from, not the location of the website server? Otherwise, Google LLC could trivially avoid their fines (https://www.cnil.fr/en/cnils-restricted-committee-imposes-financial-penalty-50-million-euros-against-google-llc, ...) by claiming that "us-east-1b" or so served the requests.


Happy to keep the sites and add a "Archived" note instead. I removed them because there are superior and more complete sources. (For example optech on tx fee savings, also taking into account taproot). If they are kept, I think at the very least they should be removed from the navigation bar. Currently it is the first item in the "FAQ" dropdown, implying that this is recommended reading material for users.

**Comment by TheBlueMatt** [comment]
> Not a lawyer, but I am pretty sure that GDPR applies based on the location of the individual that the data is collected from, not the location of the website server? Otherwise, Google LLC could trivially avoid their fines (https://www.cnil.fr/en/cnils-restricted-committee-imposes-financial-penalty-50-million-euros-against-google-llc, ...) by claiming that "us-east-1b" or so served the requests.

I'm tempted to reply with a Pirate-Bay-style "just because you write a law that says it applies to me does not mean it applies to me if I don't live in your country" response :) Part of the Google issue is they actually have corporate subsidiaries, operations, and generally do business in Europe. A random static site hosted in the US does not :p.

> Happy to keep the sites and add a "Archived" note instead. I removed them because there are superior and more complete sources. (For example optech on tx fee savings, also taking into account taproot). If they are kept, I think at the very least they should be removed from the navigation bar. Currently it is the first item in the "FAQ" dropdown, implying that this is recommended reading material for users.

SGTM.

**Comment by Sjors** [comment]
For stuff with lots of inbound links, I also prefer not deleting it.

**Comment by MarcoFalke** [comment]
> lots of inbound links

There shouldn't be too many links: https://duckduckgo.com/?q=%22bitcoincore.org%2Fen%2F2015%2F12%2F23%2Fcapacity-increases-faq

> static

Is it static if the content is `<iframe> youtube.com/watch <...`? I am actually hoping to see a GDPR lawsuit where the defendant isn't FAANG (is that called MAANG now?). If https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2022-January/019741.html is also covering the entity that hosts this website, it might be worth to eat the risk.

**Comment by TheBlueMatt** [comment]
>  lots of inbound links

There are various news articles and social media posts at the time covering the related ML post, and this document is rather historical.

**Comment by MarcoFalke** [comment]
Created #850 for discussion

**Pull request closed without merging**
