### PR TITLE
Add japanese translation for download page

### PR DESCRIPTION
**Pull request by azuchi**

### CODE REVIEW

**Comment by harding** [comment]
@azuchi Thank you for translating!  Based on your experience, is there anything you'd suggest changing in order to make translation easier or better for other translators in the future?

**Comment by azuchi** [comment]
@harding Thank you for review! For translation,  [CONTRIBUTING.md](https://github.com/bitcoin-core/bitcoincore.org/blob/master/CONTRIBUTING.md) is written to use Transifex,  but I do not know it is working.

**Comment by btcdrak** [comment]
Unfortunately Transifex made some changes that basically broke our workflow so that kind of fell apart.

**Comment by azuchi** [comment]
Oh, I see. So it may be better to update CONTRIBUTING.md according to the current. Some people are requesting to join in Transifex.

**Pull request merged**
