### PR TITLE
Bitcoin Core 24.2

### PR DESCRIPTION
**Pull request by fanquake**
Release annoucement for 24.2.

### CODE REVIEW

**Review by stickies-v — APPROVED** [review]
ACK 54f3fee73a3b016ee51a16e25e9db4a3feed8e55 modulo missing magnet link to be added when binaries are ready

**Comment by katesalazar** [comment]
Out of curiosity,
is the 'modulo' particle a deiure or a defacto ACK syntax?

**Comment by stickies-v** [comment]
I mean that I'm ACK for the PR, except for the missing magnet link. Just to be descriptive to others and future me about what I'd like to see changed before unconditional ACK.

**Comment by fanquake** [comment]
@stickies-v torrent link is now available.

**Review by stickies-v — APPROVED** [review]
ACK d5bcb1d68c731b3b2bacea8f3afe5583750a2608 

Downloaded the torrent and verified signatures.

**Review by glozow — COMMENTED** [review]
ACK d5bcb1d68c731b3b2bacea8f3afe5583750a2608, local build looks good and text looks correct, didn't test megnet

**Pull request merged**
