### PR TITLE
Change download link to bitcoincore.org

### PR DESCRIPTION
**Pull request by jnewbery**
bitcoincore.org hosts binaries. Point to bitcoincore.org for downloads.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Before we do that, I think we should check how secure the bitcoincom.org domain/setup is. IMO bitcoin.org has a pretty secure setup (not sure though).

Where is it hosted, etc.?
The GPG/gitian signatues are the best way to make sure the binaries are tamper-free, though users tend to not even verify the SHA256sum.

**Comment by MarcoFalke** [comment]
Agree with @jonasschnelli that the technical difference of the server setup is important to consider here.

**Comment by gmaxwell** [comment]
The bitcoin core setup is enormously more secure than bitcoin.org.   It is a separately racked and caged set of physically isolated hosts which requires multi-party authorization for login.

**Comment by jonasschnelli** [comment]
Thanks @gmaxwell for clarification. I do not know who is responsible for the setup and how it's done. But after @gmaxwell statement it seems that someone does take care of it.

**Comment by jonasschnelli** [comment]
Things I think could be improved:

Cloudflare DNS?
```
Name Server: VIOLET.NS.CLOUDFLARE.COM
Name Server: DAMON.NS.CLOUDFLARE.COM
```

No IPv6?
```
;; QUESTION SECTION:
;bitcoincore.org.		IN	AAAA
```

Standard SSH port (probably okay):
```
ssh 107.191.99.5 -p 22 (or ssh 198.251.83.116 -p 22)
The authenticity of host '107.191.99.5 (107.191.99.5)' can't be established.
ECDSA key fingerprint is SHA256:0/Wakhy8n3/wJ9UkgLVU7nfyBFhqdJ+lrAY/sAXT4bY.
```

**Comment by TheBlueMatt** [comment]
I'm not gonna go into all the details of the setup here. If someone wants a list of how things are set up, feel free to ping me on IRC.

**Comment by harding** [comment]
I agree with changing download links to BitcoinCore.org, as it is likely much more secure than Bitcoin.org based on what I've been told about the two different setups.

I think we can probably do better by copying the rather nice MIT-licensed https://bitcoin.org/en/download page to this site and linking to that rather than the bare /bin directory..  I'll work on that presently and try to prepare a PR for it by Wednesday afternoon.

**Comment by jonasschnelli** [comment]
Agree with @harding. A such download page should be added (through a separate PR)

**Comment by harding** [comment]
I was thinking of it as an alternative to this PR, but there's very little cost to changing the links twice, so I'll base my work on top of this PR.

**Comment by jnewbery** [comment]
> I think we can probably do better by copying the rather nice MIT-licensed https://bitcoin.org/en/download page to this site and linking to that rather than the bare /bin directory.. I'll work on that presently and try to prepare a PR for it by Wednesday afternoon.

:+1: I look forward to reviewing that.

**Pull request merged**
