### PR TITLE
Bump Ruby to 2.7.4, update github-pages and html-proofer gems

### LINKED ISSUE #825: Ruby 2.5 is EOL
We should should jump to 2.7 which is supported by [Debian Stable](https://packages.debian.org/bullseye/ruby2.7) aka Bullseye.

https://www.ruby-lang.org/en/downloads/branches/

https://github.com/bitcoin-core/bitcoincore.org/blob/e0906892db52c94216fc920451ddb76caa2331c3/Gemfile#L3-L7

### PR DESCRIPTION
**Pull request by Sjors**
This requires updating the server to Debian Stable Bullseye, cc TheBlueMatt.

I tested a few pages locally and didn't notice any difference.

I also ran the `htmlproofer` incantation from the README, which I updated to match `Makefile`. Only one minor change was needed to satisfy the updated version.

Closes #825

### CODE REVIEW

**Comment by laanwj** [comment]
Concept ACK. It makes sense to use a supported version of Ruby for easier local reproducibility.

**Comment by RandyMcMillan** [comment]
Concept ACK

I am happy to do what I can to get this moving forward - just ping me for testing. 

This is my docker environment for bitcoincore.org dev and testing. Included if others may find it useful to migrate.

https://github.com/bitcoincore-dev/core-org-builder/tree/1644282724-ruby-2-7-alpine3-14

```
git clone https://github.com/bitcoincore-dev/core-org-builder.git ~/core-org-builder
cd core-org-builder && git checkout 1644282724-ruby-2-7-alpine3-14

git clone https://github.com/bitcoin-core/bitcoincore.org.git ~/bitcoincore.org

cd ~/bitcoincore.org
git remote add sjors https://github.com/Sjors/bitcoincore.org.git
git fetch sjors && git checkout 2021/12/ruby

cd ~/core-org-builder

SITE=~/bitcoincore.org make image
SITE=~/bitcoincore.org make server
```

Screen Shot 2022-02-07 at 9 16 14 PM
Screen Shot 2022-02-07 at 9 16 37 PM

**Comment by katesalazar** [comment]
I'm planning not to wipe my Buster hosts out until summer, sorry. On the bright side, summer's almost here! 🏖️

**Comment by MarcoFalke** [comment]
Maybe rebase on #934, or on master if it is merged?

**Comment by Sjors** [comment]
I'll wait for that to be merged

**Comment by MarcoFalke** [comment]
Can be rebased now

**Comment by fanquake** [comment]
Going to merge this just in time for Ruby `2.7` to also go EOL: https://www.ruby-lang.org/en/news/2023/03/30/ruby-2-7-8-released/.

**Comment by fanquake** [comment]
There's no need for a PR. As as far as I'm aware, that version of ruby won't be available.

**Comment by Sjors** [comment]
Mmm, the release mentions it fixes security issues. Anyway, I also make a PR to the 3.1 or 3.2 series. That involves a bit more testing though.

**Pull request merged**
