### PR TITLE
Make it harder for google to fingerprint visitors

### LINKED ISSUE #850: GDPR of iframe youtube?
Might be worth to consider if something needs to be done with youtube iframes. Seee https://github.com/bitcoin-core/bitcoincore.org/pull/848#issuecomment-1014525064 and `git grep '<iframe'`.

### PR DESCRIPTION
**Pull request by MarcoFalke**
Don't send the visitor IP to google without asking. Also, don't allow google to set cookies, execute javascript etc without asking the visitor for consent. Also, fixes #850

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
Should we just host the video ourselves?

**Comment by MarcoFalke** [comment]
I am not sure if that is worth it, considering how many visitors are reading the archived posts from years ago. So I am not going to spend time on that myself. Maybe best done in a follow-up by someone else?

**Review by fanquake — APPROVED** [review]
untested ACK 2ed32596b29716ae75d441f5592bd8858996a296

**Comment by laanwj** [comment]
Untested concept and review ACK 2ed32596b29716ae75d441f5592bd8858996a296

**Comment by MarcoFalke** [comment]
With apple refusing to support webm and some Linux distros refusing proprietary codecs, it is still non-trivial to ship a video. (Not to mention that downscaled version would need to be provided for low-CPU devices).

Hosting and transcoding could be done by Wikimedia Commons (given a CC-license). They were even working on a in-browser video player, but I haven't checked the status of it recently.

Anyway, best something to be done in a follow-up, if at all.

**Comment by laanwj** [comment]
Yes, agree, merged to remove another unnecessary source of legal uncertainty.

> With apple refusing to support webm and some Linux distros refusing proprietary codecs, it is still non-trivial to ship a video. (Not to mention that downscaled version would need to be provided for low-CPU devices).

Especially if further transcoding is involved, it would make sense to hunt after the original video file instead of downloading it from youtube.

**Pull request merged**
