### PR TITLE
Fix: Wrong file naming

### PR DESCRIPTION
**Pull request by awesome-doge**
Old Simplified Chinese translation in the past, with naming errors

### CODE REVIEW

**Comment by harding** [comment]
Why do you think these files have the wrong names?

**Comment by harding** [comment]
I agree that the language part doesn't need to be in the filename or the id tag, but is this causing any problems?  If it's not causing a problem, it usually doesn't need to be changed for old content.

**Comment by awesome-doge** [comment]
If you think the extra language tags are not important, I will restore that commit.

**Comment by MarcoFalke** [comment]
Is this still relevant?

**Comment by awesome-doge** [comment]
I think it's better to close it first, I will handle all the problems inside in another pr
https://github.com/bitcoin-core/bitcoincore.org/pull/727

**Pull request closed without merging**
